apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: eventio
build:
  artifacts:
    - image: eventio/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
